export enum OtpCodes {
    EMAIL_VERIFIED="EMAIL_VERIFIED",
    TWO_FACTOR_ENABLED="TWO_FACTOR_ENABLED",
    LOGIN_SUCCESS="LOGIN_SUCCESS",
    ACCOUNT_DELETED="ACCOUNT_DELETED",
    EMAIL_CHANGED="EMAIL_CHANGED",
    USERNAME_CHANGED="USERNAME_CHANGED",
}